location ~ "^(.+)(hash\.[0-9a-f]{20})\.(js|css|ttf|eot|woff2?|png|jpe?g|gif|svg|ico)$" {
  add_header Cache-Control "public";
  expires 10y;
  try_files $uri $1$3 =404;
  access_log off;
}

location ~ ^(.+)\.\d\d+\.(js|css)$ {
  add_header Cache-Control "public";
  expires 10y;
  try_files $uri $1.$2 =404;
  access_log off;
}

location ~* \.(?:js|css)$ {
  add_header Cache-Control "public";
  expires 7d;
  if ($args ~* ver=(.+)) {
    expires 10y;
  }
  if ($args ~* v=(.+)) {
    expires 10y;
  }
  access_log off;
}
