# Use this if you're testing/debugging the build locally on OSX

version: "3.4"

services:
  web:
    build: ./alpine/
    ports:
      - "8080:8080"
    volumes:
      - ./web:/var/www/project/web
    environment:
      WP_UID: 101
      WP_GID: 101

      # For testing with gdev
      VIRTUAL_HOST: php81.test
      PORT: 8080
