[global]
error_log = /dev/stderr

[www]
listen = /var/run/php-fpm.sock
listen.owner = nginx
pm = ondemand
pm.max_children = 100
pm.max_requests = 1000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no

; Include extra configs
include=/etc/php/fpm/php-fpm.d/*.conf