error_log stderr warn;
pid /var/run/nginx.pid;

events {
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    client_max_body_size 500M;
    server_tokens off;
    fastcgi_hide_header X-Powered-By;
    fastcgi_hide_header X-Pingback;
    gzip on;
    gzip_types *;
    gzip_vary on;
    fastcgi_read_timeout 300s;

    server {
        listen [::]:8080 default_server;
        listen 8080 default_server;
        listen [::]:8082 http2 default_server;
        listen 8082 http2 default_server;
        server_name _;
        sendfile off;
        absolute_redirect off;

        root /var/www/project/web;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root /var/lib/nginx/html;
        }

        location = /wp/xmlrpc.php {
            return 404;
        }

        location = /wp-json/wp/v2/users {
            return 404;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_index index.php;

            include proxy_real_variables.conf;
            include fastcgi_params.conf;
        }

        # SEO Sitemaps
        location ~ ([^/]*)sitemap(.*).x(m|s)l$ {
            # Redirect sitemap.xml to sitemap_index.xml
            rewrite ^/sitemap.xml$ /sitemap_index.xml permanent;

            # Make the XML sitemaps work
            rewrite ^/([a-z]+)?-?sitemap.xsl$ /index.php?xsl=$1 last;
            rewrite ^/sitemap_index.xml$ /index.php?sitemap=1 last;
            rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
        }

        location ~* \.(jpg|jpeg|gif|png|css|js|ico)$ {
            expires 5d;
        }

        location = /favicon.ico {
            access_log     off;
            log_not_found  off;
            try_files      $uri  =204;
        }

        location ~ /\. {
            log_not_found off;
            deny all;
        }

        rewrite ^/(wp-.*.php)$ /wp/$1 last;
        rewrite ^/(wp-(content|admin|includes).*) /wp/$1 last;

        location = /wp {
            return 301 /;
        }

        include /app/config/nginx.conf;
    }
}
